---
GenerationParams:
  MapScale: 1.0          # how much the sectors are spread out  
  # float [0..1] solar systems are more like a cookie than a ball. the lower the value, the flatter the system
  SolarSystemSqueezeMinMax: [0.005, 0.8]
  # float [0..1] probability a warp connection will be one-way
  OneWayWarpProb: 0
  UniqueStarterPlanet: false
  
  #==== 1st Step of SolarSystem Generation: setting amount and playfield types  for System Content  ===

  PlanetCountProbs:
# ======================================================================================================================================================== Planets

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Gas Giants
     - '0 : 0.8,   1 : 0.2,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Gas Planets
     - '0 : 0.7,   1 : 0.3,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 2 - Outer Gas Planets

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Stars
     - '0 : 0.60,   1 : 0.30,  2 : 0.10,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'               # 1 - Companion Stars

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Rocky Planets
     - '0 : 0.0,   1 : 0.5,  2 : 0.4,  3 : 0.1,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Barren
     - '0 : 0.7,   1 : 0.3,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 2 - Dead
# ======================================================================================================================================================== Sector POIs

# -------------------------------------------------------------------------------------------------------------------------------------------------------- UCH and Admin POIs
     - '0 : 1.0,   1 : 0.0,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - UCH Research Vessel

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Asteroid Fields
     - '0 : 0.3,   1 : 0.3,  2 : 0.3,  3 : 0.1,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Asteroid Fields
     - '0 : 0.6,   1 : 0.2,  2 : 0.1,  3 : 0.1,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 2 - Ice Fields
     - '0 : 0.4,   1 : 0.3,  2 : 0.3,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 3 - Rich Asteroid Fields

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Anomalies

# -------------------------------------------------------------------------------------------------------------------------------------------------------- Events
     - '0 : 1.0,   1 : 0.0,  2 : 0.0,  3 : 0.0,  4 : 0.0,  5 : 0.0,  6 : 0.0,  7 : 0.0,  8 : 0.0'                 # 1 - Random Events



  PlanetLists:           # Lable name depicts, in a descriptive way, the class or global or visual approach of the playfields summarized under this lable; playfields are added in the *Types sections
# ======================================================================================================================================================== Planets
# -------------------------------------------------------------------------------------------------------------- Gas Giants
    - 'Jupiter:0.6, Saturn: 0.4'                                                                                  # 1 Gas
    - 'JupiterOuter:0.45, SaturnOuter:0.35, NeptuneOuter:0.2'                                                     # 2 Gas Outer
# -------------------------------------------------------------------------------------------------------------- Stars
    - 'SunB:0.00, SunA:0.00, SunK:0.00, SunG:0.00, SunF:0.00, SunTesch:0.60, SunD:0.00, SunN2:0.20, SunA4V:0.20'      # 1 Companion Stars
# -------------------------------------------------------------------------------------------------------------- Rocky Planets
    - 'TeschBarren:1.0'                                                                       # 1 - Barren
    - 'Dead:1.0'                                                                            # 2 - Dead
# ======================================================================================================================================================== Sector POIs
# -------------------------------------------------------------------------------------------------------------- UCH and Admin
    - 'UCHResearchShip:1.0'                                                                                         # 1 UCH Research Vessel
# -------------------------------------------------------------------------------------------------------------- Asteroid Fields
    - 'AsteroidFieldDT1:1'                                                                                   # 1 Asteroid Fields
    - 'AsteroidFieldIce:0.50, AsteroidFieldIceRich:0.50'                                                          # 2 Ice Fields
    - 'AsteroidFieldRichGeneric:1'                                                                                # 3 Rich Asteroid Fields

# -------------------------------------------------------------------------------------------------------------- Anomalies
# -------------------------------------------------------------------------------------------------------------- Events
    - 'SpaceEmpty:1.0'                                                                                            # 1 Random Events



# ======================================================================================================================================================== POIs
  POICountProbs: '0 : 0.50,  1 : 0.40,  2 : 0.10,  3 : 0.00,  4 : 0.00,  5 : 0.00,  6 : 0.00,  7 : 0.00,  8: 0.00'
# -------------------------------------------------------------------------------------------------------------------------------------------------------- POI counts
  POIs: 'SpaceEmpty: 0.00, POICombatT2: 0.30, POIHackT2: 0.35, POIMiningT2: 0.35'
# --------------------------------------------------------------------------------------------------------------------------------------------------------

# =================================================================================================================================================================================
#                                                                                                                POIs
# =================================================================================================================================================================================
  POITypes:

# ======================================================================================================================================================================================================
# ================================================================================================================================================================================= Random Sector POIs
# ======================================================================================================================================================================================================

# =================================================================================================================================================================================
#                                                                                                                Orbits
# =================================================================================================================================================================================
  OrbitTypes:
# -------------------------------------------------------------------------- DefaultOrbit
      - Name: DefaultOrbit     # definition of default name 'DefaultOrbit' is mandatory
        Color: [0.3, 0.3, 0.3]
        Distance: [270, 870]
        HasOrbit: false
        HasTerrain: false
        PlayfieldLevel: [8,10]
        Playfields:
            - EdenSpaceD_Orbit
